SECTOR_MAP = {
    "AAPL": "Tech",
    "MSFT": "Tech",
    "GOOGL": "Tech",
    "AMZN": "Retail",
    "TSLA": "Auto",
    "NVDA": "Semiconductors",
    "META": "Media",
    "NFLX": "Media",
    "AMD": "Semiconductors",
    "BABA": "Retail",
    "INTC": "Semiconductors",
    "ORCL": "Tech",
    "PYPL": "Fintech",
    "UBER": "Transport",
    "DIS": "Media",
    "JPM": "Banking",
    "BAC": "Banking",
    "WMT": "Retail",
    "COST": "Retail",
    "PEP": "Consumer",
    "KO": "Consumer",
    "PFE": "Pharma",
    "MRK": "Pharma",
}